[project]
name = "bxsolana-trader-proto"
<<<<<<< Updated upstream
version = "0.0.50"
=======
version = "0.0.48"
>>>>>>> Stashed changes
description = "proto-generated files for solana-trader-api"
dependencies = [
    "betterproto==v2.0.0b5"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[tool.black]
line-length = 80
preview = true
